# Chapter02. 1차원 데이터 정리

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
df=pd.read_csv("data/ch2_scores_em.csv", index_col='student number')

In [6]:
df

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76
6                    48           60
7                    65           81
8                    49           66
9                    65           78
10                   58           82
11                   70           94
12                   47           75
13                   51           70
14                   64           77
15                   62           84
16                   70           84
17                   71           82
18                   68           85
19                   73           90
20                   37           70
21                   65           78
22                   65           93
23                   61           77
24                   52           88
25                   57           82
26                   57           76
27                   75           87
28                   61           84
29                   47           77
30                   54           82
31                   66           91
32                   54           75
33                   54           76
34                   42           78
35                   37           57
36                   79           89
37                   56           83
38                   62           69
39                   62           86
40                   55           81
41                   63           81
42                   57           80
43                   57           79
44                   67           87
45                   55           84
46                   45           71
47                   66           80
48                   55           77
49                   64           83
50                   66           88

In [7]:
df.head(5)

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [8]:
# Jupyter Notebook의 출력을 소수점 이하 3자리로 제한
%precision 3

'%.3f'

In [9]:
# DataFrame의 출력을 소수점 이하 3자리로 제한
pd.set_option('precision',3)

In [11]:
df['english']

student number
1     42
2     69
3     56
4     41
5     57
6     48
7     65
8     49
9     65
10    58
11    70
12    47
13    51
14    64
15    62
16    70
17    71
18    68
19    73
20    37
21    65
22    65
23    61
24    52
25    57
26    57
27    75
28    61
29    47
30    54
31    66
32    54
33    54
34    42
35    37
36    79
37    56
38    62
39    62
40    55
41    63
42    57
43    57
44    67
45    55
46    45
47    66
48    55
49    64
50    66
Name: english, dtype: int64

In [10]:
np.array(df['english']) #Numpy로 계산하기 위해 Numpy의 array 데이터 구조로 저장 
                        #array? 수치 계산에 강점을 지닌 다차원 배열 

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58, 70, 47, 51, 64, 62, 70, 71,
       68, 73, 37, 65, 65, 61, 52, 57, 57, 75, 61, 47, 54, 66, 54, 54, 42,
       37, 79, 56, 62, 62, 55, 63, 57, 57, 67, 55, 45, 66, 55, 64, 66],
      dtype=int64)

In [13]:
scores=np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [15]:
scores_df=pd.DataFrame({'score':scores}, index=pd.Index(["A","B","C","D","E","F","G","H","I","J"], name="student")  )

In [16]:
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

## Section 2.1.데이터 중심의 지표

### 평균값

In [17]:
sum(scores)

550

In [18]:
len(scores)

10

In [19]:
sum(scores)/len(scores) #평균값

55.0

In [20]:
np.mean(scores) #numpy의 mean함수

55.0

In [21]:
scores_df.mean() #DataFrame의 mean메서드 

score    55.0
dtype: float64

In [22]:
scores.mean() #Numpy의 array의 mean메서드 

55.0

### 중앙값

In [23]:
np.sort(scores)

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [28]:
sorted_scores = np.sort(scores)

In [30]:
n=len(sorted_scores)

if n%2==0:
    m0=sorted_scores[n//2-1]
    m1=sorted_scores[n//2]
    median=(m0+m1)/2
else:
    median=sorted_scores[(n+1)//2-1]
median

56.5

In [31]:
np.median(scores) #numpy의 median함수

56.5

In [32]:
scores_df.median() #DataFrame와 Series의 median메서드

score    56.5
dtype: float64

### 최빈값

In [33]:
pd.Series([1,1,1,2,2,3]).mode() #DataFrame와 Series의 mode메서드 

0    1
dtype: int64

## Section 2.2.데이터의 산포도 지표

### 편차

- 편차 : 데이터가 평균으로부터 어느 정도 떨어져 있는가를 나타내는 지표

In [34]:
mean = np.mean(scores)

In [35]:
deviation = scores - mean

In [36]:
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [37]:
another_scores=[50,60,58,54,51,56,57,53,52,59]

In [42]:
another_mean=np.mean(another_scores)

In [39]:
another_deviation=another_scores-another_mean

In [40]:
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [43]:
np.mean(another_deviation)

0.0

In [ ]:
# 편차 평균은 0, 따라서 편차 평균으로는 비교할 수 없음 

In [44]:
summary_df=scores_df.copy()
summary_df['deviation']=deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [45]:
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

### 분산

- 분산 : 편차의 제곱의 평균 

In [46]:
np.mean(deviation**2) #편차 제곱의 평균

86.0

In [47]:
np.var(scores) #NumPy의 var함수 

86.0

In [48]:
scores_df.var() #DataFrame이나 Series의 var메서드 

score    95.556
dtype: float64

In [53]:
scores_df.var(ddof=0)

score    86.0
dtype: float64

In [54]:
scores_df.var(ddof=1)

score    95.556
dtype: float64

In [ ]:
#Numpy 표본분산 계산 (ddof=0) 디폴트 
#Pandas 불편분산 계산 (ddof=1) 디폴트

In [49]:
summary_df['square of deviation']=np.square(deviation) #편차제곱 열 추가 

In [50]:
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [55]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

### 표준편차 

- 표준편차 : 분산에 제곱근을 취한 값

In [57]:
np.sqrt(np.var(scores,ddof=0)) #표본분산에 제곱근

9.273618495495704

In [60]:
np.sqrt(np.var(scores,ddof=1)) #불편분산에 제곱근 

9.775252199076787

In [62]:
np.std(scores, ddof=0) #NumPy의 std함수

9.273618495495704

### 범위

- 범위 : 데이터의 최댓값과 최솟값만으로 산포도 표현

In [63]:
np.max(scores)-np.min(scores)

28

### 사분위 범위

- 사분위 범위 : 데이터의 상위%에 위치하는 값과 하위%에 위치하는 값의 차이를 취하는 방법

In [70]:
#제1사분위수
scores_Q1 = np.percentile(scores, 25) #데이터의 25%p

In [71]:
#제3사분위수
scores_Q3 = np.percentile(scores, 75) #데이터의 75%p

In [72]:
#Q3-Q1
#사분위 범위 IQR
scores_IQR = scores_Q3-scores_Q1
scores_IQR 

15.0

In [74]:
np.percentile(scores,100) #max

69.0

In [75]:
np.percentile(scores,0) #min

41.0

In [76]:
#제2사분위수
np.percentile(scores,50) #중앙값과 일치 

56.5

In [77]:
np.median(scores) #중앙값 

56.5

## 2.2.3. 데이터의 지표 정리

- describe() 메서드

In [80]:
pd.Series(scores)

0    42
1    69
2    56
3    41
4    57
5    48
6    65
7    49
8    65
9    58
dtype: int64

In [82]:
pd.Series(scores).describe() #지금까지 다룬 다양한 지표 한 번에 구할 수 있는 편리한 메서드 

count    10.000
mean     55.000
std       9.775
min      41.000
25%      48.250
50%      56.500
75%      63.250
max      69.000
dtype: float64